### ISSUE TITLE
AIDeployHelper improvement (for desolators)

### ISSUE THREAD

**Issue by forcecore** [AttacqueSuperior/Engine#8]
https://github.com/forcecore/OpenRA/commit/6baf90f80d467b29d7fe1040a259dcc5d53139dd

Just to let you know I've patched AIDeployHelper.
Units like desolators attack in AoE, possibly killing friendly units.
In TryDeploy, there is a new check logic that checks for the number of units of friendly vs enemy and if there are more enemies than friendlies then it will deploy.

**Comment by GraionDilach** [comment]
You should use AppearsHostileTo - https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/ActorExts.cs#L53 - for filtering instead of directly checking the owners. For one, that check ignores neutral units, for two, it ignores the disguise.

The other option could be that you change that boolean to a ValidStances basically with all three stances (Ally,Neutral,Enemy) being default, and then check if listed > unlisted (say, because of a healing deploy logic).

**Comment by forcecore** [comment]
I gave it a thought but unless heal or other buffs benefit enemies too, it won't need friendly/enemy check. I'll just give it AppearsHostileTo.

**Comment by forcecore** [comment]
Fixed a bug involving undeployTicks

https://github.com/forcecore/OpenRA/commit/2e63366ff26db2e4bf0eb258f72a68eab96bfef4

ticks == 0 condition was too narrow that sometimes, it will go down past 0 and will not undeploy.

**Comment by GraionDilach** [comment]
Okay, I will get your updates when I find the time.

**Comment by GraionDilach** [comment]
NTM: only the stance lookups are missing from AIDeployHelper these days.

**Comment by GraionDilach** [comment]
The stance lookups are better to be performed with `ProxExternalCondition/GrantHordeBonus` providing a condition based on the actors around which enables/disables the trait. This requires no further C# code.
